### ISSUE TITLE
코드에서 질문있어요

### ISSUE THREAD

**Issue by parkchaelin** [quizee/ninggit#7]
public int note_choice() throws ClassNotFoundException, IOException{
		
		view_notes();
		
		System.out.print("Enter number of note: ");
		int selected_nnum = scanner.nextInt();
		scanner.nextLine();  //이거 왜 있는 건가요??
		
		return selected_nnum;	
	}

**Comment by leechowon** [comment]
아 그렇군요! 그럼 close 하겠습니다!
