### ISSUE TITLE
select 클래스에서 변수 질문 있어요

### ISSUE THREAD

**Issue by parkchaelin** [quizee/ninggit#8]
public class select {
        
	static Scanner scanner = new Scanner(System.in);
	static String returned_submenu = ""; //이게 무슨 변수인가요?
	
	public static void main(String[] args) {
		showMenu();

	}

**Comment by leechowon** [comment]
지윤언니가 만들어서 정확하진 않지만 내 생각엔 그냥 변수 미리 만들어놓은 듯 합니당! 매번 지역변수 대신 static으로 만들어놓은거 같아욤!
