### ISSUE TITLE
한글 영어로 변경하기

### ISSUE THREAD

**Issue by leechowon** [quizee/ninggit#9]
내 담당인 manage_todolilst 파일 한글을 영어로 바꿔서 다시 올렸습니당

**Comment by leechowon** [comment]
@SoYeon16 아직 한글이던데 영어로 바꿔주세요!ㅎㅎ

**Comment by SoYeon16** [comment]
@leechowon 변경했어요~!!

**Comment by parkchaelin** [comment]
수정했어요

**Comment by quizee** [comment]
메인 클래스좀 완성하고 같이 push하겠습니당
